/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CreateOrderDto } from './models/create-order-dto';
export type { EmployeeDto } from './models/employee-dto';
export type { OrderDto } from './models/order-dto';
export type { ProductDto } from './models/product-dto';
export type { SalesDatePredictionDto } from './models/sales-date-prediction-dto';
export type { ShipperDto } from './models/shipper-dto';
