/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiEmployeesAllEmployeesGet$Json } from '../fn/employees/api-employees-all-employees-get-json';
import { ApiEmployeesAllEmployeesGet$Json$Params } from '../fn/employees/api-employees-all-employees-get-json';
import { apiEmployeesAllEmployeesGet$Plain } from '../fn/employees/api-employees-all-employees-get-plain';
import { ApiEmployeesAllEmployeesGet$Plain$Params } from '../fn/employees/api-employees-all-employees-get-plain';
import { EmployeeDto } from '../models/employee-dto';

@Injectable({ providedIn: 'root' })
export class EmployeesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiEmployeesAllEmployeesGet()` */
  static readonly ApiEmployeesAllEmployeesGetPath = '/api/Employees/AllEmployees';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEmployeesAllEmployeesGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmployeesAllEmployeesGet$Plain$Response(params?: ApiEmployeesAllEmployeesGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EmployeeDto>>> {
    return apiEmployeesAllEmployeesGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEmployeesAllEmployeesGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmployeesAllEmployeesGet$Plain(params?: ApiEmployeesAllEmployeesGet$Plain$Params, context?: HttpContext): Observable<Array<EmployeeDto>> {
    return this.apiEmployeesAllEmployeesGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<EmployeeDto>>): Array<EmployeeDto> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiEmployeesAllEmployeesGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmployeesAllEmployeesGet$Json$Response(params?: ApiEmployeesAllEmployeesGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EmployeeDto>>> {
    return apiEmployeesAllEmployeesGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiEmployeesAllEmployeesGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiEmployeesAllEmployeesGet$Json(params?: ApiEmployeesAllEmployeesGet$Json$Params, context?: HttpContext): Observable<Array<EmployeeDto>> {
    return this.apiEmployeesAllEmployeesGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<EmployeeDto>>): Array<EmployeeDto> => r.body)
    );
  }

}
