/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiProductsAllProductsGet$Json } from '../fn/products/api-products-all-products-get-json';
import { ApiProductsAllProductsGet$Json$Params } from '../fn/products/api-products-all-products-get-json';
import { apiProductsAllProductsGet$Plain } from '../fn/products/api-products-all-products-get-plain';
import { ApiProductsAllProductsGet$Plain$Params } from '../fn/products/api-products-all-products-get-plain';
import { ProductDto } from '../models/product-dto';

@Injectable({ providedIn: 'root' })
export class ProductsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiProductsAllProductsGet()` */
  static readonly ApiProductsAllProductsGetPath = '/api/Products/AllProducts';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProductsAllProductsGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductsAllProductsGet$Plain$Response(params?: ApiProductsAllProductsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductDto>>> {
    return apiProductsAllProductsGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProductsAllProductsGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductsAllProductsGet$Plain(params?: ApiProductsAllProductsGet$Plain$Params, context?: HttpContext): Observable<Array<ProductDto>> {
    return this.apiProductsAllProductsGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ProductDto>>): Array<ProductDto> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProductsAllProductsGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductsAllProductsGet$Json$Response(params?: ApiProductsAllProductsGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductDto>>> {
    return apiProductsAllProductsGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProductsAllProductsGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProductsAllProductsGet$Json(params?: ApiProductsAllProductsGet$Json$Params, context?: HttpContext): Observable<Array<ProductDto>> {
    return this.apiProductsAllProductsGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ProductDto>>): Array<ProductDto> => r.body)
    );
  }

}
