/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateOrderDto {
  custId?: number;
  discount?: number;
  empId?: number;
  freight?: number;
  orderDate?: string;
  productId?: number;
  qty?: number;
  requiredDate?: string;
  shipAddress?: string | null;
  shipCity?: string | null;
  shipCountry?: string | null;
  shipName?: string | null;
  shippedDate?: string | null;
  shipperId?: number;
  unitPrice?: number;
}
