/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrderDto {
  orderId?: number;
  requiredDate?: string;
  shipAddress?: string | null;
  shipCity?: string | null;
  shipName?: string | null;
  shippedDate?: string | null;
}
