/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrderDto } from '../../models/order-dto';

export interface ApiCustomersOrdersByCustomerIdGet$Plain$Params {
  id: number;
}

export function apiCustomersOrdersByCustomerIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiCustomersOrdersByCustomerIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OrderDto>>> {
  const rb = new RequestBuilder(rootUrl, apiCustomersOrdersByCustomerIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<OrderDto>>;
    })
  );
}

apiCustomersOrdersByCustomerIdGet$Plain.PATH = '/api/Customers/OrdersByCustomer/{id}';
